version: "3.0"
services:
  n1:
    container_name: cassandra_n1
    image: cassandra-with-cqlshrc 
    networks:
      - cluster
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'      
      - '9042:9042'
      - '9160:9160'
      - '9142:9142'
    volumes:
      - /apps/cassandra/cassandra_n1:/var/lib/cassandra 
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=10.239.31.4
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
  n2:
    container_name: cassandra_n2
    image: cassandra-with-cqlshrc
    networks:
      - cluster
    volumes:
      - /apps/cassandra/cassandra_n2:/var/lib/cassandra      
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1      
    depends_on:
      - n1
  n3:
    container_name: cassandra_n3
    image: cassandra-with-cqlshrc
    networks:
      - cluster
    volumes:
      - /apps/cassandra/cassandra_n3:/var/lib/cassandra        
    environment:
      - CASSANDRA_SEEDS=n1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1      
    depends_on:
      - n1      
     
networks:
  cluster:
  
 
