version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks:
      - cluster      
    volumes:
      - /apps/rabbitmq/data/:/var/lib/rabbitmq/
      - /apps/rabbitmq/logs/:/var/log/rabbitmq/      
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672
networks:
  cluster:
  